//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfuly end {0} request for {1} - {2}.
        /// </summary>
        internal static string Logger_Debug_EndHandler {
            get {
                return ResourceManager.GetString("Logger.Debug.EndHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} request for {1} - {2}.
        /// </summary>
        internal static string Logger_Debug_StartHandler {
            get {
                return ResourceManager.GetString("Logger.Debug.StartHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is null in {0} request for {1} - {2}.
        /// </summary>
        internal static string Logger_Warning_Null {
            get {
                return ResourceManager.GetString("Logger.Warning.Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation errors in {0} request for {1} - {2}.
        /// </summary>
        internal static string Logger_Warning_Validator {
            get {
                return ResourceManager.GetString("Logger.Warning.Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} already exists.
        /// </summary>
        internal static string Validator_AlreadyExists {
            get {
                return ResourceManager.GetString("Validator.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} does not exist.
        /// </summary>
        internal static string Validator_DoesNotExist {
            get {
                return ResourceManager.GetString("Validator.DoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater or equal to {ComparisonValue}.
        /// </summary>
        internal static string Validator_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Validator.GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be fewer than {MaxLength}.
        /// </summary>
        internal static string Validator_MaximumLength {
            get {
                return ResourceManager.GetString("Validator.MaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is required.
        /// </summary>
        internal static string Validator_Required {
            get {
                return ResourceManager.GetString("Validator.Required", resourceCulture);
            }
        }
    }
}
